import { CheckCircleOutlined, CloseCircleOutlined, GlobalOutlined, ReloadOutlined } from "@ant-design/icons";
import { Button, Empty, Space, Table, Tag, Typography } from "antd";
import type { ServerOverview } from "../../types/protocol";
import { AccessIpMap } from "./AccessIpMap";

export function NginxPanel({ connected, overview, loading, onRefresh }: { connected: boolean; overview?: ServerOverview; loading: boolean; onRefresh: () => void }) {
  return <section className="ops-panel"><header className="ops-panel-header"><div><Typography.Title level={3}>Nginx</Typography.Title><Typography.Text>服务健康、配置校验与访问来源</Typography.Text></div><Button icon={<ReloadOutlined spin={loading} />} onClick={onRefresh}>刷新</Button></header>{!connected ? <Empty description="请先连接服务器" /> : overview ? <div className="ops-content"><div className="nginx-status-row"><Status icon={overview.nginx.running ? <CheckCircleOutlined /> : <CloseCircleOutlined />} label="服务" value={!overview.nginx.installed ? "未安装" : overview.nginx.running ? "运行中" : "未运行"} ok={overview.nginx.running} /><Status icon={overview.nginx.configValid ? <CheckCircleOutlined /> : <CloseCircleOutlined />} label="配置" value={overview.nginx.configValid ? "校验通过" : "校验失败或无权限"} ok={overview.nginx.configValid} /><div className="nginx-version"><span>版本</span><strong>{overview.nginx.version || "--"}</strong></div></div><div className="ops-section-heading"><Space><GlobalOutlined /><Typography.Text strong>访问来源地图</Typography.Text></Space><Typography.Text type="secondary">标记大小代表请求量</Typography.Text></div><AccessIpMap items={overview.accessIps} /><div className="ops-section-heading"><Space><GlobalOutlined /><Typography.Text strong>最近访问 IP</Typography.Text></Space><Typography.Text type="secondary">最近 2,000 条日志</Typography.Text></div><Table size="small" pagination={false} rowKey="ip" dataSource={overview.accessIps} locale={{ emptyText: "未读取到 access log" }} columns={[{ title: "IP 地址", dataIndex: "ip", render: (value) => <code>{value}</code> }, { title: "位置", key: "location", render: (_, item) => [item.city, item.country].filter(Boolean).join(", ") || "--" }, { title: "请求数", dataIndex: "requests", width: 110, sorter: (a, b) => a.requests - b.requests }]} /><div className="ops-notice"><Typography.Text strong>配置管理</Typography.Text><Typography.Paragraph>当前阶段提供运行状态和配置校验结果。可视化站点、反向代理和发布回滚将在结构化解析与审计机制完成后开放。</Typography.Paragraph></div></div> : <Empty description="暂无 Nginx 状态"><Button onClick={onRefresh}>加载状态</Button></Empty>}</section>;
}

function Status({ icon, label, value, ok }: { icon: React.ReactNode; label: string; value: string; ok?: boolean }) { return <div className={`nginx-status${ok ? " nginx-status-ok" : ""}`}>{icon}<div><span>{label}</span><strong>{value}</strong></div></div>; }
